### ISSUE TITLE
Can we use free trash

### ISSUE THREAD

**Issue by Ann-Beck** [Obvious-trash/trash2#5]
No we need to pay for it.

**Comment by Ann-Beck** [comment]
@don-isobvious Do you think we can get this fixed?

**Comment by DelilahMichaels** [comment]
@adam-isobvious NO free trash just isn't good enough.

**Comment by Ann-Beck** [comment]
@don-isobvious Can we at least get cheap trash?

**Comment by DelilahMichaels** [comment]
@adam-isobvious OK we can get some cheap trash.  But we will have to have QA double check the quality.
